### ISSUE TITLE
Watch out for typos

### ISSUE THREAD

**Issue by MMortaga** [GSG-G7/Your-Lyrics#29]
https://github.com/GSG-G7/Your-Lyrics/blob/fc0a2ba992b9a996aee12d91e0880e06d45c36d6/src/controllers/song.js#L1

Simple mistakes like these can waste hours of debugging. Keep your code clean by using camelCase and carefully reviewing each others' code to avoid typos.

**Comment by MaiUbeid** [comment]
We solved it  ^_^
